spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes[0]:
        uri: https://localhost:8080/dev/auth
        id: LoginService
        predicates[0]: Path=/dev/auth/**
      routes[1]:
        id: Admin
        predicates[0]: Path=/dev/category/**
        uri: https://localhost:8084/dev/category
      routes[2]:
        id: Admin
        uri: https://localhost:8084/dev/admin/profile
        predicates[0]: Path=/dev/admin/profile/**
      routes[3]:
        predicates[0]: Path=/dev/admin/**
        id: Admin
        uri: https://localhost:8084/dev/admin
      routes[4]:
        uri: https://localhost:8084/dev/subcategory
        id: Admin
        predicates[0]: Path=/dev/subcategory/**
      routes[5]:
        uri: https://localhost:8084/dev/specification
        id: Admin
        predicates[0]: Path=/dev/specification/**
      routes[6]:
        uri: https://localhost:8084/dev/productMeasurement
        id: Admin
        predicates[0]: Path=/dev/productMeasurement/**
      routes[7]:
        uri: https://localhost:8084/dev/product
        id: Admin
        predicates[0]: Path=/dev/product/**
      routes[8]:
        uri: https://localhost:8084/dev/adminMData
        id: Admin
        predicates[0]: Path=/dev/adminMData/**
      routes[9]:
        uri: https://localhost:8083/dev/designerProduct
        id: Designer
        predicates[0]: Path=/dev/designerProduct/**
      routes[10]:
        uri: https://localhost:8083/dev/designer
        id: Designer
        predicates[0]: Path=/dev/designer/**
      routes[11]:
        uri: https://localhost:8083/dev/orderStatus
        id: Designer
        predicates[0]: Path=/dev/orderStatus/**
      routes[12]:
        uri: https://localhost:8082/dev/user
        id: User
        predicates[0]: Path=/dev/user/**
      routes[13]:
        uri: https://localhost:8082/dev/userOrder
        id: User
        predicates[0]: Path=/dev/userOrder/**
      routes[14]:
        uri: https://localhost:8083/dev/order
        id: Designer
        predicates[0]: Path=/dev/order/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
  application:
    name: ApiGatway
server:
  port: '9095'
  ssl:
    key-store: classpath:gateway-server.jks
    key-store-type: JKS
    key-alias: gateway-server
    key-password: Dapp@1234
    key-store-password: Dapp@1234
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2
#  ssl:
##   key-store: C:\Users\Ahadul\Downloads\divatt.jks
#   key-store: divatt.jks
#   key-store-password: divatt
#   key-store-type: JKS
#   key-alias: divatt
#   key-password: divatt


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka