






spring:
  cloud:
    gateway:
      routes[0]:
        uri: http://localhost:8080/dev/auth
        id: LoginService
        predicates[0]: Path=/dev/auth/**
      routes[1]:
        id: Admin
        predicates[0]: Path=/dev/category/**
        uri: http://localhost:8084/dev/category
      routes[2]:
        id: Admin
        uri: http://localhost:8084/dev/admin/profile
        predicates[0]: Path=/dev/admin/profile/**
      routes[3]:
        predicates[0]: Path=/dev/admin/**
        id: Admin
        uri: http://localhost:8084/dev/admin
      routes[4]:
        uri: http://localhost:8084/dev/subcategory
        id: Admin
        predicates[0]: Path=/dev/subcategory/**
      routes[5]:
        uri: http://localhost:8083/dev/product
        id: Designer
        predicates[0]: Path=/dev/product/**
      routes[6]:
        uri: http://localhost:8082/dev/user
        id: User
        predicates[0]: Path=/dev/user/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-headers: '*'
            allowedMethods: GET, POST, PUT, DELETE
            max-age: '3600'
            allowed-origins: '*'
  application:
    name: ApiGatway
server:
  port: '8085'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka