#This is the application namespring:  application:    name: ApiGatway    #Fro server portserver:  port: 8082  # For eureka client
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true# For routing# Secrit key for JWTjwt.secret.key: secretjwt.token.validity: 1296000000