spring:
  profiles: default
  application: 
     name: DatabaseServices
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
    
server: 
  port: 8083
  servlet: 
    contextPath: /default
name: databasesrvice-default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/databaseservice_default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
        
#jwt.secret.key: secret
#jwt.token.validity: 36000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
---
spring:
  profiles: dev
  application: 
     name: DatabaseServices
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
    
server: 
  port: 8083
  servlet: 
    contextPath: /dev
name: databasesrvice-dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/databaseservice_dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
        
#jwt.secret.key: secret
#jwt.token.validity: 36000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
---
spring:
  profiles: prod
  application: 
     name: DatabaseServices
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
    
server: 
  port: 8083
  servlet: 
    contextPath: /prod
name: databasesrvice-prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - www.prod.com
   - www.prod1.com
logging: 
      file: 
        name: logs/databaseservice_prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.ulearn.*: INFO
        org.hibernate: ERROR
        
        
#jwt.secret.key: secret
#jwt.token.validity: 36000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka