# Name of the application
spring:
  application:
    name: designerRegistration
    
# Port of the application
server:  port: 8083
  
  
# For eureka client
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
  