spring:
  profiles: default
  application: 
     name: Admin 
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://15.207.103.249:3306/divatt
#    username: divatt_user
#    password: P@ssw0rd123
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8081
  servlet: 
    contextPath: /default
name: default-yml
environment: default
enabled: true
contextpath: /default
servers: 
   - www.default.com
   - www.default1.com
logging: 
      file: 
        name: logs/default_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 1296000000

---
spring:
  profiles: dev
  application: 
     name: Admin 
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://15.207.103.249:3306/divatt
#    username: divatt_user
#    password: P@ssw0rd123
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195 #13.234.240.158  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8084
  servlet: 
    contextPath: /dev
name: dev-yml
environment: dev
enabled: true
contextpath: /dev
servers: 
   - www.dev.com
   - www.dev1.com
logging: 
      file: 
        name: logs/dev_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 1296000000

connection: 
  pool: 
    initialPoolSize: 5
    minPoolSize: 10
    maxPoolSize: 20
    maxIdleTime: 3000
    
spring.servlet.multipart:
  enabled: true
  max-file-size: 100MB
#file.upload-path: C:\\Users\\shant\\Desktop\\uploadfile\\
file.upload-path: /home/ubuntu/Attachment/



#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA5LPN4UP72CHINWRB
      secretKey: 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

application:
  bucket:
    name: lara-tri
    basepath: D-App
---
spring:
  profiles: prod
  application: 
     name: Admin 
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://15.207.103.249:3306/divatt
#    username: divatt_user
#    password: P@ssw0rd123
  data:
    mongodb:
      authentication-database: admin
      database: divatt
      host: 65.1.190.195  #65.1.190.195:27017,,,,, 65.0.194.170
      password: word_pass
      port: 27017
      username: dbuser 
 
server: 
  port: 8081
  servlet: 
    contextPath: /prod
name: prod-yml
environment: prod
enabled: true
contextpath: /prod
servers: 
   - www.prod.com
   - www.prod1.com
logging: 
      file: 
        name: logs/prod_logs.log
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      level:
        org.springframework.web: ERROR
        org.daivatt.*: INFO
        org.hibernate: ERROR
        
jwt.secret.key: c2VjcmV0
jwt.token.validity: 1296000000




